const STRINGS = {
  en: {
    appName: "HarvestHonor",
    appSubtitle: "Is the price fair?",
    labelCrop: "Crop",
    labelCity: "City",
    labelQuantity: "Quantity (kg)",
    labelQuotedPrice: "Buyer's Quoted Price (PKR per 100kg)",
    placeholderCrop: "Select your crop",
    placeholderCity: "Select crop first",
    placeholderQuantity: "e.g. 100",
    placeholderPrice: "e.g. 2800",
    btnCheckPrice: "Check Price",
    btnGenerateProof: "Generate Proof Card",
    btnShare: "Share on WhatsApp",
    btnScreenshot: "Save as Image",
    btnBack: "← Check another crop",
    btnBackToResult: "← Back to result",
    verdictUnderpaid: "UNDERPAID",
    verdictFair: "FAIR PRICE",
    verdictAbove: "ABOVE MARKET",
    verdictUnderpaidSub: "You are being underpaid by",
    verdictFairSub: "This price is within market range",
    verdictAboveSub: "You are being offered above market rate",
    labelMarketPrice: "Market Price",
    labelQuoted: "Quoted Price",
    labelDifference: "Difference",
    labelCropCity: "Crop / City",
    labelOfficialMarket: "Official Market Price",
    labelBuyerOffer: "Buyer's Offer",
    labelPer100kg: "per 100kg",
    labelWhatToDo: "What should you do?",
    labelYouCanSay: "You can say this",
    labelWhyHappening: "Why this might be happening",
    labelAILoading: "Getting AI analysis...",
    labelAIUnavailable: "AI unavailable — showing default message",
    labelSource: "Source: Pakistan Bureau of Statistics",
    labelDataDate: "week of 23 April 2026",
    labelUpdateNote: 
      "Price data last updated: week of 23 April 2026. " +
      "Update weekly from pbs.gov.pk for best accuracy.",
    labelWatermark: "Generated by HarvestHonor",
    labelReportTitle: "HarvestHonor Price Report",
    confidenceHigh: "✓ High Confidence — Recent PBS Data",
    confidenceModerate: "⚠ Moderate Confidence — Limited Data",
    shareNotAvailable: 
      "Sharing is available on mobile browsers. " +
      "Use Screenshot instead.",
    errorNoData: 
      "Data not available for [crop] in [city]. " +
      "Try a nearby city or check pbs.gov.pk directly.",
    errorInvalidQty: "Please enter a valid quantity",
    errorInvalidPrice: "Please enter the buyer's quoted price",
    errorSelectCrop: "Please select a crop",
    errorSelectCity: "Please select a city",
    toggleLang: "اردو میں دیکھیں",
    saving: "Saving...",
    totalDiffLoss: "loss on",
    totalDiffGain: "gain on",
    totalDiffLine: "Total difference on [qty]kg: Rs [amt] [type]"
  },

  ur: {
    appName: "ہارویسٹ آنر",
    appSubtitle: "کیا قیمت منصفانہ ہے؟",
    labelCrop: "فصل",
    labelCity: "شہر",
    labelQuantity: "مقدار (کلو)",
    labelQuotedPrice: "خریدار کی قیمت (روپے فی 100 کلو)",
    placeholderCrop: "اپنی فصل منتخب کریں",
    placeholderCity: "پہلے فصل منتخب کریں",
    placeholderQuantity: "مثال: 100",
    placeholderPrice: "مثال: 2800",
    btnCheckPrice: "قیمت چیک کریں",
    btnGenerateProof: "ثبوت کارڈ بنائیں",
    btnShare: "واٹس ایپ پر شیئر کریں",
    btnScreenshot: "تصویر محفوظ کریں",
    btnBack: "← دوسری فصل چیک کریں",
    btnBackToResult: "← نتیجے پر واپس جائیں",
    verdictUnderpaid: "نقصان میں ہیں",
    verdictFair: "منصفانہ قیمت",
    verdictAbove: "بازار سے بہتر",
    verdictUnderpaidSub: "آپ کو بازار سے کم قیمت دی جا رہی ہے",
    verdictFairSub: "یہ قیمت بازار کے مطابق ہے",
    verdictAboveSub: "آپ کو بازار سے زیادہ قیمت مل رہی ہے",
    labelMarketPrice: "بازار کی قیمت",
    labelQuoted: "پیش کردہ قیمت",
    labelDifference: "فرق",
    labelCropCity: "فصل / شہر",
    labelOfficialMarket: "سرکاری بازار قیمت",
    labelBuyerOffer: "خریدار کی پیشکش",
    labelPer100kg: "فی 100 کلو",
    labelWhatToDo: "آپ کو کیا کرنا چاہیے؟",
    labelYouCanSay: "آپ یہ کہہ سکتے ہیں",
    labelWhyHappening: "یہ کیوں ہو رہا ہے",
    labelAILoading: "AI تجزیہ حاصل ہو رہا ہے...",
    labelAIUnavailable: "AI دستیاب نہیں — پہلے سے طے شدہ پیغام",
    labelSource: "ماخذ: پاکستان بیورو آف سٹیٹسٹکس",
    labelDataDate: "ہفتہ 23 اپریل 2026",
    labelUpdateNote:
      "قیمت کا ڈیٹا آخری بار اپ ڈیٹ ہوا: 23 اپریل 2026۔ " +
      "درستگی کے لیے pbs.gov.pk سے ہفتہ وار اپ ڈیٹ کریں۔",
    labelWatermark: "ہارویسٹ آنر کے ذریعے تیار کردہ",
    labelReportTitle: "ہارویسٹ آنر قیمت رپورٹ",
    confidenceHigh: "✓ اعلی اعتماد — حالیہ PBS ڈیٹا",
    confidenceModerate: "⚠ اعتدال پسند اعتماد — محدود ڈیٹا",
    shareNotAvailable:
      "شیئرنگ موبائل براؤزر پر دستیاب ہے۔ " +
      "تصویر محفوظ کریں استعمال کریں۔",
    errorNoData:
      "[city] میں [crop] کا ڈیٹا دستیاب نہیں۔ " +
      "قریبی شہر آزمائیں یا pbs.gov.pk دیکھیں۔",
    errorInvalidQty: "براہ کرم درست مقدار درج کریں",
    errorInvalidPrice: "براہ کرم خریدار کی قیمت درج کریں",
    errorSelectCrop: "براہ کرم فصل منتخب کریں",
    errorSelectCity: "براہ کرم شہر منتخب کریں",
    toggleLang: "View in English",
    saving: "محفوظ ہو رہا ہے...",
    totalDiffLoss: "نقصان",
    totalDiffGain: "فائدہ",
    totalDiffLine: 
      "[qty] کلو پر کل فرق: Rs [amt] [type]"
  }
};

let currentLang = "en";

function t() {
  return STRINGS[currentLang];
}

function toggleLanguage() {
  currentLang = currentLang === "en" ? "ur" : "en";
  document.documentElement.dir = currentLang === "ur" ? "rtl" : "ltr";
}

function getLang() {
  return currentLang;
}
